Kasterborous dev
MattJeanes/TARDIS pull request #383
Opened 2021-03-05 07:12 UTC by parar020100

This feature allows the extension user to have specific parts such as interior doors not be affected by the isomorphic system.

PART.BypassIsomorphic = true

_This pull request has been ported from gitlab of kasterborous team. [[Original merge request]](https://gitlab.com/kasterborous/tardis-core/-/merge_requests/1)_

2021-03-05 10:37 UTC, MattJeanes requested changes

2021-03-05 10:37 UTC, MattJeanes commented on lua/entities/gmod_tardis_interior/modules/sh_security.lua
> +		part.BypassIsomorphic = part.BypassIsomorphic or false
This line does not need to exist

2021-03-05 10:37 UTC, MattJeanes commented on lua/tardis/parts/legacy/legact_atomaccel.lua
> +PART.BypassIsomorphic = false
We do not need to include this false in all the parts, only true in the parts that require it

2021-03-05 10:37 UTC, MattJeanes commented on lua/entities/gmod_tardis_interior/modules/sh_security.lua
> +		if part.ID == "door" or part.BypassIsomorphic then return end
The door part should have BypassIsomorphic set to true instead of this explicit bypass here

2021-03-05 10:49 UTC, MattJeanes commented on lua/tardis/parts/legacy/legacy_blacksticks.lua
> +    local result = self.exterior:ToggleCloak() or false
This function does not exist, and will just throw an error message, why is it here?

2021-03-06 17:20 UTC, ryanm2711 commented on lua/tardis/parts/legacy/legacy_wibblylever.lua
> +PART.BypassIsomorphic = false
```suggestion
```

2021-03-13 09:12 UTC, closed without merging