Trigger HADS when lifted by physgun
MattJeanes/TARDIS pull request #614
Opened 2022-02-04 12:20 UTC by DoctorErt

2022-02-04 12:27 UTC, MattJeanes requested changes
Hey there, thank you for your contribution! I see this is your first ever GitHub contribution so congratulations! 😄 

I've added a couple little comments to tweak the behaviour slightly but this is looking pretty good!

2022-02-04 12:27 UTC, MattJeanes commented on lua/entities/gmod_tardis/modules/sh_hads.lua
> +    function ENT:TryTriggerHADS()
This can be just TriggerHADS like the other functions that work similarly

2022-02-04 12:27 UTC, MattJeanes commented on lua/entities/gmod_tardis/modules/sh_hads.lua
>          if self:CallHook("CanTriggerHads") == false then return end
Can we change up the logic in this function so that it returns true or false whether or not HADS was activated? This will help below

2022-02-04 12:27 UTC, MattJeanes commented on lua/entities/gmod_tardis/modules/sh_hads.lua
> +            ent:TryTriggerHADS()
As above when TriggerHADS returns true/false we can use that in the if check below rather than checking hads-triggered here

2022-02-04 13:03 UTC, DoctorErt commented
Everything should be fixed now

2022-02-07 22:08 UTC, MattJeanes approved these changes
Many thanks for your contribution!

2022-02-07 22:08 UTC, merged