Blocked exit
MattJeanes/TARDIS pull request #932
Opened 2023-10-14 15:07 UTC by Evgeni420

- block doors when it's impossible to exit
- added `SlowThink` hooks serverside

2023-10-15 03:00 UTC, MattJeanes requested changes
This is a great quality of life feature and really helps with the finishing touches on the addon. Thanks for working on this, it's a fantastic first contribution.

I've got a couple of small things I'd like some tweaks on but it's all minor stuff. Great work!

2023-10-15 03:00 UTC, AmyJeanes commented on lua/entities/gmod_tardis/init.lua
> +    if CurTime() >= (self.nextslowthink or 0) then
This is good but it should be implemented into the Doors addon instead as it's more of a base code feature, that's also where the fast think is implemented so it makes sense to be in there too.

I've added you as a collaborator to https://github.com/MattJeanes/Doors now so you can do this

2023-10-15 03:00 UTC, AmyJeanes commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +        local door_int=TARDIS:GetPart(self.interior,"door")
nitpick: inconsistent spacing between these lines

2023-10-15 03:00 UTC, AmyJeanes commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +        elseif override or override==nil then
Could this be replaced with `elseif override ~= false`?

2023-10-15 03:00 UTC, AmyJeanes commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +            if IsValid(door_ext) then door_ext:SetSolid(SOLID_NONE) end
nitpick: inconsistent spacing around the brackets on `SetSolid` on these lines

2023-10-15 03:00 UTC, AmyJeanes commented on lua/entities/gmod_tardis_interior/init.lua
> +function ENT:Think()
Should be in Doors addon as per the other comment :)

2023-10-15 03:00 UTC, AmyJeanes commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +        local z_ops = {0, 0.2, 0.4, 0.5, 0.6, 0.8, 1}
This might be slightly too pessimistic as it is possible to place the TARDIS in front of a wall in a place that you should be able to walk in through the side and similarly walk out but it blocks both the entrance and exit.

Here's an example from `freespace_revolution` on the default interior where it blocks me but I should be able to get in/out:

![image](https://github.com/MattJeanes/TARDIS/assets/2363642/bac6608b-77f4-4115-b7c5-9435f034cc52)

2023-10-15 09:25 UTC, parar020100 commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +        local z_ops = {0, 0.2, 0.4, 0.5, 0.6, 0.8, 1}
Should we make a smaller scanning area?

2023-10-15 16:17 UTC, MattJeanes commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +        local z_ops = {0, 0.2, 0.4, 0.5, 0.6, 0.8, 1}
Also wondering if this is open to abuse in MP, can you just stand in front of the door to block people getting out for example?

2023-10-15 16:32 UTC, parar020100 commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +        local z_ops = {0, 0.2, 0.4, 0.5, 0.6, 0.8, 1}
> Also wondering if this is open to abuse in MP, can you just stand in front of the door to block people getting out for example?

Not abusable
See line `td.mask = MASK_NPCWORLDSTATIC` - it only filters the world

As for the exit condition
We might make the scanning box smaller but in general testing it seems to be forbidding exit when the player would get stuck in the textures

2023-10-15 16:37 UTC, MattJeanes commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +        local z_ops = {0, 0.2, 0.4, 0.5, 0.6, 0.8, 1}
Yeah I think it just needs to be made a very slight bit smaller otherwise seems good!

2023-11-19 09:44 UTC, parar020100 commented
We've decided to put this on hold for a while

2023-11-19 09:44 UTC, closed without merging