A fix for dupes, saves, TARDISes without owner and more
MattJeanes/TARDIS pull request #962
Opened 2023-10-22 21:50 UTC by parar020100

Closes #949 #542 #957 #956 #958 #959

2023-10-23 23:57 UTC, MattJeanes requested changes
This works super well amazingly, fantastic work on this. Just a few tiny little questions / things but nothing major. Brilliant stuff.

2023-10-23 23:57 UTC, AmyJeanes commented on lua/entities/gmod_tardis/init.lua
> +    ent:InitializeReal()
I think you can just add the `if not IsValid(self:GetCreator())` check to the main Initialize function and then just call `Initialize` again, I don't think we need a separate `Real` function

2023-10-23 23:57 UTC, AmyJeanes commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +    ENT:AddHook("ToggleDoor", "doorcollision",function(self,open)
Should these changes from #932 be in here?

2023-10-23 23:57 UTC, AmyJeanes commented on lua/entities/gmod_tardis_interior/init.lua
> +    if prop:IsVehicle() then
What's the reason for the `IsVehicle` here? I presume related to the seats in some interiors, but can we detect this in a better way e.g. set a special variable on them?

2023-10-23 23:57 UTC, AmyJeanes commented on lua/entities/gmod_tardis_interior/init.lua
> +    local saved_pos = self:GetData("interior_saved_pos")
What would happen if you duplicated it on a different map? Should there be safeguards against this?

2023-10-23 23:57 UTC, AmyJeanes commented on lua/entities/gmod_tardis_interior/modules/sh_power.lua
> +        if self:GetData("power_disabled_first") then
Is this needed in the interior as well? The same code exists in the exterior

2023-10-23 23:57 UTC, MattJeanes commented on lua/entities/gmod_tardis_interior/init.lua
> +    if prop:IsVehicle() then
Update: Explained in DMs, difficult to lock onto vehicle entities tried many diff workarounds - good enough!

2023-10-24 07:48 UTC, parar020100 commented on lua/entities/gmod_tardis/modules/sh_doors.lua
> +    ENT:AddHook("ToggleDoor", "doorcollision",function(self,open)
Dupes had problems with door collisions, code from #932 could fix that so I just re-added it.
There's no wall detection code though, just this refactoring

2023-10-24 07:52 UTC, parar020100 commented on lua/entities/gmod_tardis_interior/modules/sh_power.lua
> +        if self:GetData("power_disabled_first") then
we need all the hooks (including clientside ones) to work on the interior to set it to power off state

I tried avoiding it, but since the interior usually spawns after exterior, its lights and texturesets got completely messed up without this one

2023-10-24 11:34 UTC, MattJeanes commented on lua/entities/gmod_tardis_interior/modules/sh_power.lua
> +        if self:GetData("power_disabled_first") then
Okay cool, just wanted to make sure it was intended

2023-10-26 07:25 UTC, parar020100 commented on lua/entities/gmod_tardis/init.lua
> +    ent:InitializeReal()
e29bb179a52822815531ad20f7da637d85c8fefb

2023-10-26 07:25 UTC, parar020100 commented on lua/entities/gmod_tardis_interior/init.lua
> +    local saved_pos = self:GetData("interior_saved_pos")
e29bb179a52822815531ad20f7da637d85c8fefb

2023-10-26 09:05 UTC, AmyJeanes approved these changes
Fantastic work, really well done!

2023-10-26 09:05 UTC, merged